### ISSUE TITLE
RangeNotSatisfiableError when downloading a YouTube video.

### ISSUE THREAD

**Issue by Codycody31** [tyler-Github/YasifysTools#23]
**Issue Description:**

When attempting to download the YouTube video "We Played EVERY Claw Machine in this CITY-WQiU5Hm5uF8.mp4" using the YouTube Downloader tool, I encountered the following error:

```
File already exists: public/downloads/We Played EVERY Claw Machine in this CITY-WQiU5Hm5uF8.mp4
07/12/2023 7:18:03 AM
RangeNotSatisfiableError: Range Not Satisfiable
07/12/2023 7:18:03 AM
    at createHttpError (/app/node_modules/send/index.js:984:7)
07/12/2023 7:18:03 AM
    at SendStream.error (/app/node_modules/send/index.js:270:31)
07/12/2023 7:18:03 AM
    at SendStream.send (/app/node_modules/send/index.js:666:19)
07/12/2023 7:18:03 AM
    at onstat (/app/node_modules/send/index.js:725:10)
07/12/2023 7:18:03 AM
    at FSReqCallback.oncomplete (fs.js:193:5)
```

**Steps to Reproduce:**

1. Download the youtube video https://www.youtube.com/watch?v=WQiU5Hm5uF8.

**Expected Behavior:**

Expected to be able to download it

**Comment by Codycody31** [comment]
Temp fix merged
